import type { EventTemplate } from "./event-templates";

export const EVENT_TEMPLATE_EXPANSIONS: Record<string, EventTemplate> = {
  "bridal shower": {
    tasks: [
      { title: "Choose shower style, hosts, and guest count", priority: "urgent", days_before: 75, category: "Planning" },
      { title: "Set shower budget and host contributions", priority: "high", days_before: 70, category: "Budget" },
      { title: "Confirm venue availability and deposit deadline", priority: "urgent", days_before: 65, category: "Venue" },
      { title: "Collect registry and honoree preferences", priority: "high", days_before: 60, category: "Guest of honor" },
      { title: "Send invitations with RSVP and registry link", priority: "high", days_before: 50, category: "Guests" },
      { title: "Plan menu, beverages, and allergy accommodations", priority: "high", days_before: 35, category: "Food" },
      { title: "Order cake or shower desserts", priority: "medium", days_before: 28, category: "Food" },
      { title: "Book florist, balloon decor, or backdrop", priority: "medium", days_before: 28, category: "Decor" },
      { title: "Plan games, prizes, and gift-opening supplies", priority: "medium", days_before: 21, category: "Activities" },
      { title: "Reserve tables, chairs, linens, and serving pieces", priority: "medium", days_before: 21, category: "Rentals" },
      { title: "Confirm accessible seating, parking, and restrooms", priority: "high", days_before: 14, category: "Guest care" },
      { title: "Review RSVPs and follow up with missing replies", priority: "high", days_before: 10, category: "Guests" },
      { title: "Confirm vendors, payments, deliveries, and setup access", priority: "urgent", days_before: 7, category: "Vendors" },
      { title: "Assemble favors and label gifts or prizes", priority: "low", days_before: 3, category: "Supplies" },
      { title: "Set up decor, food stations, and gift table", priority: "urgent", days_before: 0, category: "Setup" },
      { title: "Clean up, return rentals, and send thank-you notes", priority: "medium", days_before: -2, category: "Follow-up" },
    ],
    budget: [
      { category: "Venue", label: "Shower venue and service fees", share: 0.18 },
      { category: "Food & Beverage", label: "Brunch, tea, and beverages", share: 0.24 },
      { category: "Decor", label: "Florals, balloons, and backdrop", share: 0.14 },
      { category: "Cake & Desserts", label: "Cake and sweets", share: 0.10 },
      { category: "Rentals", label: "Tables, linens, and serving pieces", share: 0.08 },
      { category: "Invitations", label: "Invitations and postage", share: 0.05 },
      { category: "Activities", label: "Games, prizes, and favors", share: 0.08 },
      { category: "Photography", label: "Photography or photo booth", share: 0.08 },
      { category: "Contingency", label: "Contingency reserve", share: 0.05 },
    ],
    runsheet: [
      { offset_min: -120, duration_min: 60, title: "Vendor arrival and venue setup", owner: "Hosts" },
      { offset_min: -60, duration_min: 45, title: "Decor, gift table, and food station setup", owner: "Hosts" },
      { offset_min: -15, duration_min: 15, title: "Accessibility, restroom, and parking check", owner: "Hosts" },
      { offset_min: 0, duration_min: 30, title: "Guest arrival and welcome refreshments", owner: "Hosts" },
      { offset_min: 30, duration_min: 45, title: "Brunch or meal service", owner: "Caterer" },
      { offset_min: 75, duration_min: 35, title: "Shower games and prizes", owner: "Host" },
      { offset_min: 110, duration_min: 30, title: "Advice, wishes, and gift opening", owner: "Host" },
      { offset_min: 140, duration_min: 20, title: "Dessert and group photos", owner: "Photographer" },
      { offset_min: 160, duration_min: 60, title: "Cleanup and rental pack-out", owner: "Hosts" },
    ],
    vendors: [
      { category: "Venue", status: "required", priority: 1 },
      { category: "Catering", status: "required", priority: 1, notes: "Brunch, tea, or light lunch" },
      { category: "Bakery", status: "recommended", priority: 2, notes: "Cake or shower desserts" },
      { category: "Florist", status: "recommended", priority: 2 },
      { category: "Balloon Decor", status: "recommended", priority: 2 },
      { category: "Rentals", status: "recommended", priority: 3 },
      { category: "Photography", status: "optional", priority: 3 },
      { category: "Photo Booth", status: "optional", priority: 4 },
    ],
  },
  "engagement party": {
    tasks: [
      { title: "Choose celebration style and confirm the couple's guest list", priority: "urgent", days_before: 90, category: "Planning" },
      { title: "Set budget, host responsibilities, and contribution deadline", priority: "high", days_before: 85, category: "Budget" },
      { title: "Book venue and confirm noise, parking, and end-time rules", priority: "urgent", days_before: 75, category: "Venue" },
      { title: "Send invitations with RSVP deadline and dress code", priority: "high", days_before: 60, category: "Guests" },
      { title: "Book caterer and choose menu with dietary options", priority: "high", days_before: 50, category: "Food" },
      { title: "Plan bar, mocktails, and responsible transportation", priority: "high", days_before: 45, category: "Beverages" },
      { title: "Book photographer and decide on a couple portrait area", priority: "medium", days_before: 42, category: "Photography" },
      { title: "Choose flowers, decor, and welcome signage", priority: "medium", days_before: 35, category: "Decor" },
      { title: "Reserve rentals and confirm any venue insurance requirement", priority: "medium", days_before: 30, category: "Rentals" },
      { title: "Plan toasts, music, and a brief engagement announcement", priority: "medium", days_before: 21, category: "Program" },
      { title: "Review RSVPs and confirm final headcount", priority: "high", days_before: 14, category: "Guests" },
      { title: "Confirm vendors, balances, arrival times, and cleanup plan", priority: "urgent", days_before: 7, category: "Vendors" },
      { title: "Complete setup and final venue walkthrough", priority: "urgent", days_before: 0, category: "Setup" },
      { title: "Return rentals and send host and guest thank-yous", priority: "low", days_before: -3, category: "Follow-up" },
    ],
    budget: [
      { category: "Venue", label: "Venue rental and service fees", share: 0.22 },
      { category: "Food & Beverage", label: "Catering, bar, and mocktails", share: 0.28 },
      { category: "Photography", label: "Engagement party photography", share: 0.10 },
      { category: "Decor", label: "Flowers, signage, and decor", share: 0.12 },
      { category: "Music", label: "DJ or live music", share: 0.08 },
      { category: "Rentals", label: "Tables, chairs, linens, and glassware", share: 0.08 },
      { category: "Invitations", label: "Invitations and postage", share: 0.04 },
      { category: "Transportation", label: "Guest transportation or rideshare support", share: 0.03 },
      { category: "Contingency", label: "Contingency reserve", share: 0.05 },
    ],
    runsheet: [
      { offset_min: -150, duration_min: 75, title: "Venue access, vendor arrival, and setup", owner: "Hosts" },
      { offset_min: -60, duration_min: 30, title: "Food, bar, decor, and photo area check", owner: "Coordinator" },
      { offset_min: -15, duration_min: 15, title: "Sound check and final safety walkthrough", owner: "DJ" },
      { offset_min: 0, duration_min: 45, title: "Guest arrival and welcome drinks", owner: "Hosts" },
      { offset_min: 45, duration_min: 60, title: "Food service and mingling", owner: "Caterer" },
      { offset_min: 105, duration_min: 20, title: "Toasts and engagement announcement", owner: "Host" },
      { offset_min: 125, duration_min: 90, title: "Music, photos, and open celebration", owner: "DJ" },
      { offset_min: 215, duration_min: 60, title: "Teardown and cleanup", owner: "Coordinator" },
    ],
    vendors: [
      { category: "Venue", status: "required", priority: 1 },
      { category: "Catering", status: "required", priority: 1 },
      { category: "Bartending", status: "recommended", priority: 2 },
      { category: "Photography", status: "recommended", priority: 2 },
      { category: "Florist", status: "recommended", priority: 3 },
      { category: "DJ / Music", status: "recommended", priority: 3 },
      { category: "Rentals", status: "optional", priority: 4 },
      { category: "Transportation", status: "optional", priority: 4 },
    ],
  },
  "anniversary celebration": {
    tasks: [
      { title: "Choose the anniversary theme and honor the couple's story", priority: "high", days_before: 100, category: "Planning" },
      { title: "Set budget and decide whether the event is formal or casual", priority: "urgent", days_before: 95, category: "Budget" },
      { title: "Book venue and confirm accessibility, parking, and curfew", priority: "urgent", days_before: 80, category: "Venue" },
      { title: "Build guest list and collect updated addresses", priority: "high", days_before: 75, category: "Guests" },
      { title: "Send invitations with RSVP, dress code, and meal details", priority: "high", days_before: 60, category: "Guests" },
      { title: "Collect photos, memories, and video messages for a tribute", priority: "medium", days_before: 45, category: "Program" },
      { title: "Book caterer and confirm menu, cake, and dietary needs", priority: "high", days_before: 42, category: "Food" },
      { title: "Book photographer and decide whether to add a photo booth", priority: "medium", days_before: 40, category: "Photography" },
      { title: "Choose florals, centerpieces, and milestone signage", priority: "medium", days_before: 30, category: "Decor" },
      { title: "Plan speeches, music, and the anniversary toast", priority: "medium", days_before: 21, category: "Program" },
      { title: "Confirm RSVPs, seating, vendor balances, and final headcount", priority: "urgent", days_before: 10, category: "Final details" },
      { title: "Prepare memory display, guest book, and keepsake favors", priority: "low", days_before: 5, category: "Supplies" },
      { title: "Complete setup, tribute check, and final walkthrough", priority: "urgent", days_before: 0, category: "Setup" },
      { title: "Return rentals and share photos with family", priority: "low", days_before: -7, category: "Follow-up" },
    ],
    budget: [
      { category: "Venue", label: "Celebration venue", share: 0.22 },
      { category: "Food & Beverage", label: "Dinner, drinks, and service", share: 0.25 },
      { category: "Photography", label: "Photographer or photo booth", share: 0.12 },
      { category: "Decor", label: "Flowers, centerpieces, and signage", share: 0.12 },
      { category: "Cake & Desserts", label: "Anniversary cake", share: 0.07 },
      { category: "Music", label: "DJ or background music", share: 0.07 },
      { category: "Rentals", label: "Linens, chairs, and tableware", share: 0.06 },
      { category: "Invitations", label: "Invitations and postage", share: 0.04 },
      { category: "Keepsakes", label: "Memory display and favors", share: 0.05 },
    ],
    runsheet: [
      { offset_min: -150, duration_min: 75, title: "Vendor arrival and room setup", owner: "Coordinator" },
      { offset_min: -60, duration_min: 30, title: "Memory display, cake, and photo check", owner: "Family host" },
      { offset_min: 0, duration_min: 45, title: "Guest arrival and welcome drinks", owner: "Hosts" },
      { offset_min: 45, duration_min: 70, title: "Dinner service", owner: "Caterer" },
      { offset_min: 115, duration_min: 30, title: "Tribute video, speeches, and toast", owner: "MC" },
      { offset_min: 145, duration_min: 90, title: "Photos, music, and celebration", owner: "Photographer" },
      { offset_min: 235, duration_min: 60, title: "Cleanup and rental return staging", owner: "Coordinator" },
    ],
    vendors: [
      { category: "Venue", status: "required", priority: 1 },
      { category: "Catering", status: "required", priority: 1 },
      { category: "Photography", status: "recommended", priority: 2 },
      { category: "Cake & Desserts", status: "recommended", priority: 2 },
      { category: "Florist", status: "recommended", priority: 3 },
      { category: "DJ / Music", status: "optional", priority: 3 },
      { category: "Rentals", status: "optional", priority: 4 },
      { category: "Photo Booth", status: "optional", priority: 4 },
    ],
  },
  "retirement party": {
    tasks: [
      { title: "Confirm honoree preferences, guest count, and event tone", priority: "urgent", days_before: 100, category: "Planning" },
      { title: "Set host committee budget and contribution deadlines", priority: "high", days_before: 95, category: "Budget" },
      { title: "Book venue with accessible entry, parking, and quiet space", priority: "urgent", days_before: 80, category: "Venue" },
      { title: "Collect colleague and family contact information", priority: "high", days_before: 70, category: "Guests" },
      { title: "Send invitations with RSVP and dietary questions", priority: "high", days_before: 55, category: "Guests" },
      { title: "Gather career photos, memories, and tribute messages", priority: "medium", days_before: 45, category: "Program" },
      { title: "Book catering and confirm menu, beverages, and cake", priority: "high", days_before: 42, category: "Food" },
      { title: "Book AV, microphone, and slideshow support", priority: "high", days_before: 35, category: "AV" },
      { title: "Choose decor, timeline signage, and a memory table", priority: "medium", days_before: 28, category: "Decor" },
      { title: "Plan speeches, roast boundaries, and presentation order", priority: "medium", days_before: 21, category: "Program" },
      { title: "Confirm RSVPs, seating, vendors, and final payments", priority: "urgent", days_before: 10, category: "Final details" },
      { title: "Test slideshow, microphones, and backup presentation files", priority: "high", days_before: 3, category: "AV" },
      { title: "Set up memory table, stage, food, and accessibility seating", priority: "urgent", days_before: 0, category: "Setup" },
      { title: "Collect gifts, return rentals, and send thank-yous", priority: "low", days_before: -5, category: "Follow-up" },
    ],
    budget: [
      { category: "Venue", label: "Venue rental and room setup", share: 0.20 },
      { category: "Food & Beverage", label: "Meal, drinks, and cake", share: 0.28 },
      { category: "AV / Production", label: "Sound, microphone, and slideshow", share: 0.12 },
      { category: "Photography", label: "Event photography", share: 0.10 },
      { category: "Decor", label: "Memory table, flowers, and signage", share: 0.10 },
      { category: "Rentals", label: "Tables, chairs, linens, and podium", share: 0.07 },
      { category: "Invitations", label: "Invitations and postage", share: 0.04 },
      { category: "Keepsakes", label: "Guest book and retirement gift", share: 0.06 },
      { category: "Contingency", label: "Contingency reserve", share: 0.03 },
    ],
    runsheet: [
      { offset_min: -150, duration_min: 75, title: "AV load-in, room setup, and memory table", owner: "Committee" },
      { offset_min: -45, duration_min: 25, title: "Microphone and slideshow test", owner: "AV" },
      { offset_min: 0, duration_min: 40, title: "Guest arrival and welcome", owner: "Hosts" },
      { offset_min: 40, duration_min: 60, title: "Dinner or buffet service", owner: "Caterer" },
      { offset_min: 100, duration_min: 45, title: "Tribute slideshow and speeches", owner: "MC" },
      { offset_min: 145, duration_min: 30, title: "Retirement gift and honoree remarks", owner: "Host" },
      { offset_min: 175, duration_min: 45, title: "Cake, photos, and informal visiting", owner: "Photographer" },
      { offset_min: 220, duration_min: 60, title: "Teardown and cleanup", owner: "Committee" },
    ],
    vendors: [
      { category: "Venue", status: "required", priority: 1 },
      { category: "Catering", status: "required", priority: 1 },
      { category: "AV / Production", status: "required", priority: 1 },
      { category: "Photography", status: "recommended", priority: 2 },
      { category: "Cake & Desserts", status: "recommended", priority: 3 },
      { category: "Decor", status: "recommended", priority: 3 },
      { category: "Rentals", status: "optional", priority: 4 },
    ],
  },
  "holiday party": {
    tasks: [
      { title: "Choose holiday, date, guest mix, and event format", priority: "urgent", days_before: 100, category: "Planning" },
      { title: "Set budget and confirm company or host approval", priority: "high", days_before: 95, category: "Budget" },
      { title: "Book venue before peak holiday dates fill", priority: "urgent", days_before: 85, category: "Venue" },
      { title: "Confirm venue insurance, alcohol, and fire-safety rules", priority: "high", days_before: 75, category: "Permits & safety" },
      { title: "Send invitations with RSVP, dress code, and gift policy", priority: "high", days_before: 65, category: "Guests" },
      { title: "Choose menu with dietary, nonalcoholic, and allergy options", priority: "high", days_before: 45, category: "Food" },
      { title: "Book DJ, band, or holiday entertainment", priority: "medium", days_before: 42, category: "Entertainment" },
      { title: "Order seasonal decor, lighting, and signage", priority: "medium", days_before: 35, category: "Decor" },
      { title: "Plan gift exchange, games, and prize rules", priority: "medium", days_before: 28, category: "Activities" },
      { title: "Reserve rentals and confirm weather or indoor backup", priority: "medium", days_before: 21, category: "Rentals" },
      { title: "Review RSVPs, seating, parking, and transportation needs", priority: "high", days_before: 14, category: "Guests" },
      { title: "Confirm vendors, balances, deliveries, and cleanup access", priority: "urgent", days_before: 7, category: "Final details" },
      { title: "Set up lighting, decor, welcome table, and food stations", priority: "urgent", days_before: 0, category: "Setup" },
      { title: "Return rentals, remove decor, and reconcile expenses", priority: "medium", days_before: -2, category: "Follow-up" },
    ],
    budget: [
      { category: "Venue", label: "Holiday venue and service fees", share: 0.22 },
      { category: "Food & Beverage", label: "Dinner, bar, and nonalcoholic drinks", share: 0.27 },
      { category: "Entertainment", label: "DJ, band, or holiday activity", share: 0.12 },
      { category: "Decor", label: "Seasonal decor and lighting", share: 0.12 },
      { category: "Rentals", label: "Furniture, linens, and tableware", share: 0.08 },
      { category: "Invitations", label: "Invitations and postage", share: 0.04 },
      { category: "Gifts & Prizes", label: "Gift exchange and prizes", share: 0.06 },
      { category: "Photography", label: "Photography or photo booth", share: 0.05 },
      { category: "Transportation", label: "Parking or shuttle support", share: 0.02 },
      { category: "Contingency", label: "Contingency reserve", share: 0.02 },
    ],
    runsheet: [
      { offset_min: -180, duration_min: 90, title: "Venue access, lighting, and decor setup", owner: "Coordinator" },
      { offset_min: -90, duration_min: 45, title: "Catering, bar, and allergy-label check", owner: "Caterer" },
      { offset_min: -30, duration_min: 20, title: "Music, photo area, and parking signage check", owner: "DJ" },
      { offset_min: 0, duration_min: 45, title: "Guest arrival and welcome drinks", owner: "Hosts" },
      { offset_min: 45, duration_min: 75, title: "Dinner or buffet service", owner: "Caterer" },
      { offset_min: 120, duration_min: 30, title: "Games, gift exchange, or awards", owner: "MC" },
      { offset_min: 150, duration_min: 120, title: "Music, dancing, photos, and mingling", owner: "Entertainment" },
      { offset_min: 270, duration_min: 75, title: "Teardown and seasonal decor pack-out", owner: "Coordinator" },
    ],
    vendors: [
      { category: "Venue", status: "required", priority: 1 },
      { category: "Catering", status: "required", priority: 1 },
      { category: "Bartending", status: "recommended", priority: 2 },
      { category: "DJ / Music", status: "recommended", priority: 2 },
      { category: "Decor", status: "required", priority: 2 },
      { category: "Rentals", status: "recommended", priority: 3 },
      { category: "Photography", status: "optional", priority: 4 },
      { category: "Transportation", status: "optional", priority: 4 },
    ],
  },
  "fundraiser or gala": {
    tasks: [
      { title: "Set fundraising goal, audience, and success measures", priority: "urgent", days_before: 180, category: "Strategy" },
      { title: "Form planning committee and assign sponsor outreach", priority: "high", days_before: 170, category: "Planning" },
      { title: "Book venue and confirm capacity, accessibility, and parking", priority: "urgent", days_before: 150, category: "Venue" },
      { title: "Confirm permits, insurance, alcohol rules, and auction requirements", priority: "urgent", days_before: 135, category: "Compliance" },
      { title: "Create ticket, donation, and RSVP registration flow", priority: "high", days_before: 120, category: "Registration" },
      { title: "Secure sponsors, auction donors, and matching gifts", priority: "high", days_before: 110, category: "Fundraising" },
      { title: "Book caterer, bar, AV, and event production", priority: "high", days_before: 95, category: "Vendors" },
      { title: "Launch invitations with mission story and early registration", priority: "high", days_before: 90, category: "Guests" },
      { title: "Build auction catalog, bid process, and payment plan", priority: "high", days_before: 60, category: "Auction" },
      { title: "Confirm honorees, speakers, entertainment, and run of show", priority: "medium", days_before: 45, category: "Program" },
      { title: "Finalize menu, dietary accommodations, table plan, and signage", priority: "high", days_before: 30, category: "Final details" },
      { title: "Confirm guest count, sponsor logos, payments, and auction volunteers", priority: "urgent", days_before: 14, category: "Operations" },
      { title: "Rehearse program, test AV, and brief registration team", priority: "urgent", days_before: 3, category: "Rehearsal" },
      { title: "Complete gala setup, registration, and accessibility walkthrough", priority: "urgent", days_before: 0, category: "Setup" },
      { title: "Reconcile donations, vendor invoices, and sponsor fulfillment", priority: "high", days_before: -7, category: "Follow-up" },
      { title: "Send donor receipts, impact thank-yous, and survey", priority: "medium", days_before: -10, category: "Follow-up" },
    ],
    budget: [
      { category: "Venue", label: "Gala venue and service fees", share: 0.18 },
      { category: "Food & Beverage", label: "Dinner, bar, and service", share: 0.22 },
      { category: "AV / Production", label: "Stage, sound, lighting, and screens", share: 0.15 },
      { category: "Decor", label: "Florals, linens, and mission signage", share: 0.10 },
      { category: "Marketing", label: "Invitations, printing, and promotion", share: 0.08 },
      { category: "Auction", label: "Auction platform and display materials", share: 0.06 },
      { category: "Entertainment", label: "Music or featured entertainment", share: 0.06 },
      { category: "Photography", label: "Event photography and video", share: 0.06 },
      { category: "Registration", label: "Check-in, badges, and payment supplies", share: 0.04 },
      { category: "Contingency", label: "Contingency reserve", share: 0.05 },
    ],
    runsheet: [
      { offset_min: -240, duration_min: 120, title: "Production load-in, stage, and room setup", owner: "Production" },
      { offset_min: -120, duration_min: 60, title: "Auction display, registration, and sponsor signage", owner: "Operations" },
      { offset_min: -45, duration_min: 30, title: "Speaker, video, and microphone rehearsal", owner: "AV" },
      { offset_min: 0, duration_min: 60, title: "Registration, reception, and welcome drinks", owner: "Registration" },
      { offset_min: 60, duration_min: 75, title: "Dinner service", owner: "Caterer" },
      { offset_min: 135, duration_min: 45, title: "Mission program and beneficiary story", owner: "Host" },
      { offset_min: 180, duration_min: 45, title: "Fundraising appeal and auction", owner: "Auction lead" },
      { offset_min: 225, duration_min: 90, title: "Entertainment, networking, and final bids", owner: "Entertainment" },
      { offset_min: 315, duration_min: 120, title: "Checkout, donor support, and teardown", owner: "Operations" },
    ],
    vendors: [
      { category: "Venue", status: "required", priority: 1 },
      { category: "Catering", status: "required", priority: 1 },
      { category: "AV / Production", status: "required", priority: 1 },
      { category: "Event Planner", status: "recommended", priority: 2 },
      { category: "Decor", status: "recommended", priority: 2 },
      { category: "DJ / Music", status: "recommended", priority: 3 },
      { category: "Photography", status: "recommended", priority: 3 },
      { category: "Security", status: "optional", priority: 4 },
      { category: "Transportation", status: "optional", priority: 4 },
    ],
  },
  "conference or networking event": {
    tasks: [
      { title: "Define audience, learning goals, and attendance target", priority: "urgent", days_before: 180, category: "Strategy" },
      { title: "Set budget approval, sponsor levels, and registration price", priority: "high", days_before: 170, category: "Budget" },
      { title: "Book venue, breakout rooms, and room block deadline", priority: "urgent", days_before: 150, category: "Venue" },
      { title: "Confirm insurance, permits, accessibility, and emergency plan", priority: "high", days_before: 135, category: "Operations" },
      { title: "Invite speakers, moderators, and workshop leaders", priority: "high", days_before: 120, category: "Program" },
      { title: "Open registration with agenda, parking, and transit details", priority: "high", days_before: 100, category: "Registration" },
      { title: "Book AV, staging, internet, recording, and livestream support", priority: "high", days_before: 90, category: "Production" },
      { title: "Choose catering for breaks, lunch, and dietary needs", priority: "high", days_before: 75, category: "Food" },
      { title: "Confirm sponsors, exhibitor tables, and branded signage", priority: "medium", days_before: 60, category: "Sponsors" },
      { title: "Finalize agenda, room assignments, and speaker materials", priority: "high", days_before: 45, category: "Program" },
      { title: "Send attendee logistics reminder and accessibility check-in", priority: "medium", days_before: 21, category: "Attendees" },
      { title: "Print badges, programs, directional signs, and feedback cards", priority: "medium", days_before: 10, category: "Materials" },
      { title: "Run AV rehearsal and final venue walkthrough", priority: "urgent", days_before: 2, category: "Rehearsal" },
      { title: "Set up registration, stages, rooms, and sponsor areas", priority: "urgent", days_before: 0, category: "Setup" },
      { title: "Send survey, reconcile invoices, and share recordings", priority: "medium", days_before: -7, category: "Follow-up" },
    ],
    budget: [
      { category: "Venue", label: "Venue, breakout rooms, and room block", share: 0.22 },
      { category: "AV / Production", label: "Sound, screens, internet, and recording", share: 0.20 },
      { category: "Food & Beverage", label: "Breaks, lunch, and beverages", share: 0.20 },
      { category: "Speakers", label: "Speaker fees and travel", share: 0.10 },
      { category: "Marketing", label: "Registration, branding, and promotion", share: 0.08 },
      { category: "Rentals", label: "Furniture, pipe and drape, and linens", share: 0.06 },
      { category: "Photography", label: "Event photography and video", share: 0.05 },
      { category: "Transportation", label: "Parking, shuttles, and transit support", share: 0.04 },
      { category: "Materials", label: "Badges, programs, and supplies", share: 0.03 },
      { category: "Contingency", label: "Contingency reserve", share: 0.02 },
    ],
    runsheet: [
      { offset_min: -240, duration_min: 120, title: "AV, registration, and sponsor load-in", owner: "Operations" },
      { offset_min: -120, duration_min: 60, title: "Room signs, accessibility, and breakout setup", owner: "Operations" },
      { offset_min: -45, duration_min: 30, title: "Speaker sound check and livestream test", owner: "Production" },
      { offset_min: 0, duration_min: 45, title: "Registration and coffee networking", owner: "Registration" },
      { offset_min: 45, duration_min: 60, title: "Opening keynote", owner: "Speaker" },
      { offset_min: 105, duration_min: 90, title: "Panels or breakout sessions", owner: "Moderators" },
      { offset_min: 195, duration_min: 45, title: "Lunch and sponsor networking", owner: "Catering" },
      { offset_min: 240, duration_min: 120, title: "Workshops and networking rotations", owner: "Operations" },
      { offset_min: 360, duration_min: 30, title: "Closing remarks and next steps", owner: "Host" },
      { offset_min: 390, duration_min: 90, title: "Teardown and equipment return", owner: "Production" },
    ],
    vendors: [
      { category: "Venue", status: "required", priority: 1 },
      { category: "AV / Production", status: "required", priority: 1 },
      { category: "Catering", status: "required", priority: 1 },
      { category: "Event Planner", status: "recommended", priority: 2 },
      { category: "Photography", status: "recommended", priority: 3 },
      { category: "Videography", status: "recommended", priority: 3 },
      { category: "Rentals", status: "recommended", priority: 3 },
      { category: "Transportation", status: "optional", priority: 4 },
      { category: "Security", status: "optional", priority: 4 },
    ],
  },
  "school event or prom": {
    tasks: [
      { title: "Form student, staff, and parent planning committee", priority: "urgent", days_before: 180, category: "Planning" },
      { title: "Approve date, venue, budget, and school policies", priority: "urgent", days_before: 165, category: "Approvals" },
      { title: "Confirm chaperones, security, supervision, and emergency plan", priority: "high", days_before: 140, category: "Safety" },
      { title: "Book venue and verify capacity, accessibility, and parking", priority: "urgent", days_before: 135, category: "Venue" },
      { title: "Confirm insurance, permits, transportation, and curfew", priority: "high", days_before: 120, category: "Operations" },
      { title: "Open ticket sales, permission forms, and RSVP tracking", priority: "high", days_before: 90, category: "Guests" },
      { title: "Book DJ, photographer, and photo booth", priority: "high", days_before: 75, category: "Entertainment" },
      { title: "Choose menu, snacks, beverages, and allergy plan", priority: "high", days_before: 60, category: "Food" },
      { title: "Choose theme, decor, lighting, and table rentals", priority: "medium", days_before: 50, category: "Decor" },
      { title: "Publish dress code, arrival rules, parking, and pickup plan", priority: "high", days_before: 35, category: "Guest care" },
      { title: "Confirm ticket count, vendors, chaperone shifts, and balances", priority: "urgent", days_before: 14, category: "Final details" },
      { title: "Prepare check-in list, wristbands, emergency contacts, and signage", priority: "high", days_before: 7, category: "Operations" },
      { title: "Complete setup, safety sweep, and vendor walkthrough", priority: "urgent", days_before: 0, category: "Setup" },
      { title: "Return rentals, reconcile funds, and share event photos", priority: "medium", days_before: -5, category: "Follow-up" },
    ],
    budget: [
      { category: "Venue", label: "Venue rental and school facility fees", share: 0.18 },
      { category: "Entertainment", label: "DJ, lighting, and music", share: 0.18 },
      { category: "Food & Beverage", label: "Food, snacks, and drinks", share: 0.20 },
      { category: "Decor", label: "Theme decor, lighting, and signage", share: 0.14 },
      { category: "Photography", label: "Photographer and photo booth", share: 0.10 },
      { category: "Security", label: "Security, chaperone, and first-aid supplies", share: 0.06 },
      { category: "Rentals", label: "Tables, linens, and lounge furniture", share: 0.06 },
      { category: "Transportation", label: "Bus, parking, or pickup support", share: 0.04 },
      { category: "Tickets", label: "Ticketing and wristbands", share: 0.02 },
      { category: "Contingency", label: "Contingency reserve", share: 0.02 },
    ],
    runsheet: [
      { offset_min: -180, duration_min: 90, title: "Venue access, decor, and rental setup", owner: "Committee" },
      { offset_min: -90, duration_min: 45, title: "DJ, photo booth, and check-in test", owner: "Vendors" },
      { offset_min: -30, duration_min: 20, title: "Safety sweep and chaperone briefing", owner: "Staff" },
      { offset_min: 0, duration_min: 60, title: "Student arrival and ticket check-in", owner: "Registration" },
      { offset_min: 60, duration_min: 180, title: "Music, dancing, photos, and refreshments", owner: "DJ" },
      { offset_min: 240, duration_min: 30, title: "Prom activities, awards, or announcements", owner: "MC" },
      { offset_min: 270, duration_min: 30, title: "Pickup and supervised departure", owner: "Staff" },
      { offset_min: 300, duration_min: 90, title: "Teardown and cleanup", owner: "Committee" },
    ],
    vendors: [
      { category: "Venue", status: "required", priority: 1 },
      { category: "DJ / Music", status: "required", priority: 1 },
      { category: "Catering", status: "required", priority: 2 },
      { category: "Photography", status: "recommended", priority: 2 },
      { category: "Photo Booth", status: "recommended", priority: 2 },
      { category: "Decor", status: "required", priority: 2 },
      { category: "Rentals", status: "recommended", priority: 3 },
      { category: "Security", status: "required", priority: 1 },
      { category: "Transportation", status: "optional", priority: 4 },
    ],
  },
  "quinceañera": {
    tasks: [
      { title: "Set quinceañera budget, guest count, and family responsibilities", priority: "urgent", days_before: 300, category: "Planning" },
      { title: "Book reception venue and confirm church or ceremony date", priority: "urgent", days_before: 270, category: "Venue" },
      { title: "Choose padrinos and confirm their contribution deadlines", priority: "high", days_before: 240, category: "Family" },
      { title: "Book dress, alterations, and accessories", priority: "high", days_before: 210, category: "Attire" },
      { title: "Build guest list and send save-the-date information", priority: "high", days_before: 180, category: "Guests" },
      { title: "Book photographer, videographer, DJ, and choreographer", priority: "high", days_before: 165, category: "Vendors" },
      { title: "Choose theme, colors, florals, backdrop, and centerpieces", priority: "medium", days_before: 140, category: "Decor" },
      { title: "Send formal invitations with RSVP, ceremony, and dress details", priority: "high", days_before: 110, category: "Guests" },
      { title: "Plan menu, cake, beverages, and dietary accommodations", priority: "high", days_before: 90, category: "Food" },
      { title: "Schedule hair, makeup, transportation, and court fittings", priority: "medium", days_before: 75, category: "Personal" },
      { title: "Reserve tables, chairs, linens, throne, and ceremony rentals", priority: "medium", days_before: 60, category: "Rentals" },
      { title: "Plan waltz, surprise dance, speeches, and ceremony program", priority: "high", days_before: 45, category: "Program" },
      { title: "Confirm RSVPs, seating, church requirements, and vendor balances", priority: "urgent", days_before: 21, category: "Final details" },
      { title: "Hold dance rehearsal and full ceremony walkthrough", priority: "urgent", days_before: 7, category: "Rehearsal" },
      { title: "Prepare tips, emergency kit, guest book, and final confirmations", priority: "high", days_before: 2, category: "Supplies" },
      { title: "Complete ceremony and reception setup, then manage teardown", priority: "urgent", days_before: 0, category: "Setup" },
      { title: "Return rentals and send family, padrino, and guest thank-yous", priority: "low", days_before: -7, category: "Follow-up" },
    ],
    budget: [
      { category: "Venue", label: "Church and reception venue", share: 0.18 },
      { category: "Catering", label: "Food, beverages, and service", share: 0.18 },
      { category: "Attire", label: "Dress, court attire, and alterations", share: 0.14 },
      { category: "Photography", label: "Photography and videography", share: 0.12 },
      { category: "Music", label: "DJ, sound, and choreographer", share: 0.10 },
      { category: "Decor", label: "Theme decor, florals, and backdrop", share: 0.10 },
      { category: "Rentals", label: "Tables, linens, throne, and ceremony items", share: 0.07 },
      { category: "Cake & Desserts", label: "Quinceañera cake and sweets", share: 0.04 },
      { category: "Hair & Makeup", label: "Hair and makeup", share: 0.03 },
      { category: "Transportation", label: "Limousine or family transportation", share: 0.02 },
      { category: "Contingency", label: "Contingency reserve", share: 0.02 },
    ],
    runsheet: [
      { offset_min: -240, duration_min: 90, title: "Ceremony and reception vendor load-in", owner: "Coordinator" },
      { offset_min: -180, duration_min: 120, title: "Hair, makeup, and final attire preparation", owner: "Beauty team" },
      { offset_min: -90, duration_min: 60, title: "Court, family, and photo portraits", owner: "Photographer" },
      { offset_min: -30, duration_min: 20, title: "Ceremony, music, and transportation check", owner: "Coordinator" },
      { offset_min: 0, duration_min: 60, title: "Mass or ceremony", owner: "Officiant" },
      { offset_min: 60, duration_min: 45, title: "Reception arrival and cocktail photos", owner: "Photographer" },
      { offset_min: 105, duration_min: 60, title: "Dinner service", owner: "Caterer" },
      { offset_min: 165, duration_min: 30, title: "Entrance, waltz, and formal dances", owner: "DJ" },
      { offset_min: 195, duration_min: 30, title: "Surprise dance, speeches, and cake", owner: "MC" },
      { offset_min: 225, duration_min: 120, title: "Open dance floor and celebration", owner: "DJ" },
      { offset_min: 345, duration_min: 120, title: "Teardown and rental load-out", owner: "Coordinator" },
    ],
    vendors: [
      { category: "Venue", status: "required", priority: 1 },
      { category: "Catering", status: "required", priority: 1 },
      { category: "Photography", status: "required", priority: 1 },
      { category: "Videography", status: "recommended", priority: 2 },
      { category: "DJ / Music", status: "required", priority: 1 },
      { category: "Choreographer", status: "recommended", priority: 2 },
      { category: "Florist", status: "recommended", priority: 3 },
      { category: "Decor", status: "required", priority: 2 },
      { category: "Rentals", status: "required", priority: 2 },
      { category: "Bakery", status: "required", priority: 2 },
      { category: "Hair & Makeup", status: "required", priority: 2 },
      { category: "Transportation", status: "recommended", priority: 3 },
    ],
  },
  "dinner party": {
    tasks: [
      { title: "Choose dinner style, guest count, and hosting location", priority: "urgent", days_before: 45, category: "Planning" },
      { title: "Set menu budget and decide host, potluck, chef, or caterer", priority: "high", days_before: 42, category: "Budget" },
      { title: "Send invitations with RSVP and dietary question", priority: "high", days_before: 35, category: "Guests" },
      { title: "Confirm venue layout, parking, accessibility, and restroom access", priority: "high", days_before: 30, category: "Venue" },
      { title: "Finalize menu, beverage pairings, and allergy-safe alternatives", priority: "high", days_before: 21, category: "Food" },
      { title: "Book caterer, private chef, or rentals if needed", priority: "high", days_before: 18, category: "Vendors" },
      { title: "Choose tablescape, flowers, candles, and place cards", priority: "medium", days_before: 14, category: "Decor" },
      { title: "Plan seating, music, welcome toast, and conversation flow", priority: "medium", days_before: 10, category: "Program" },
      { title: "Review RSVPs and confirm final portions", priority: "high", days_before: 7, category: "Guests" },
      { title: "Shop for ingredients, beverages, ice, and serving supplies", priority: "high", days_before: 3, category: "Supplies" },
      { title: "Confirm vendor arrival, payment, rentals, and cleanup plan", priority: "urgent", days_before: 1, category: "Final details" },
      { title: "Set table, prepare food, and complete accessibility check", priority: "urgent", days_before: 0, category: "Setup" },
      { title: "Clean up, return rentals, and send guest thank-yous", priority: "low", days_before: -2, category: "Follow-up" },
    ],
    budget: [
      { category: "Food & Beverage", label: "Ingredients, chef, catering, and drinks", share: 0.42 },
      { category: "Venue", label: "Private dining room or venue fee", share: 0.12 },
      { category: "Rentals", label: "Tables, chairs, linens, and serving ware", share: 0.12 },
      { category: "Decor", label: "Flowers, candles, and tablescape", share: 0.10 },
      { category: "Cake & Desserts", label: "Dessert course", share: 0.08 },
      { category: "Music", label: "Background music or musician", share: 0.05 },
      { category: "Invitations", label: "Invitations and stationery", share: 0.04 },
      { category: "Photography", label: "Dinner photography", share: 0.03 },
      { category: "Contingency", label: "Contingency reserve", share: 0.04 },
    ],
    runsheet: [
      { offset_min: -150, duration_min: 90, title: "Chef, caterer, and rental arrival", owner: "Host" },
      { offset_min: -60, duration_min: 45, title: "Table setting, food prep, and beverage setup", owner: "Host" },
      { offset_min: -15, duration_min: 15, title: "Accessibility, lighting, and final walkthrough", owner: "Host" },
      { offset_min: 0, duration_min: 30, title: "Guest arrival and aperitif", owner: "Host" },
      { offset_min: 30, duration_min: 75, title: "First course and conversation", owner: "Caterer" },
      { offset_min: 105, duration_min: 75, title: "Main course and welcome toast", owner: "Host" },
      { offset_min: 180, duration_min: 45, title: "Dessert and coffee", owner: "Caterer" },
      { offset_min: 225, duration_min: 45, title: "Goodbyes and cleanup", owner: "Host" },
    ],
    vendors: [
      { category: "Catering", status: "recommended", priority: 1, notes: "Caterer or private chef" },
      { category: "Venue", status: "optional", priority: 2, notes: "Private dining room if not hosting at home" },
      { category: "Rentals", status: "recommended", priority: 2 },
      { category: "Florist", status: "optional", priority: 3 },
      { category: "Bakery", status: "optional", priority: 3 },
      { category: "Music", status: "optional", priority: 4 },
      { category: "Photography", status: "optional", priority: 4 },
    ],
  },
};