/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewEventRouteImport } from './routes/new-event'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BridgeworldRouteImport } from './routes/bridgeworld'
import { Route as BridgevaultRouteImport } from './routes/bridgevault'
import { Route as BridgednaRouteImport } from './routes/bridgedna'
import { Route as BridgeIntelligenceRouteImport } from './routes/bridge-intelligence'
import { Route as IndexRouteImport } from './routes/index'

const NewEventRoute = NewEventRouteImport.update({
  id: '/new-event',
  path: '/new-event',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeworldRoute = BridgeworldRouteImport.update({
  id: '/bridgeworld',
  path: '/bridgeworld',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgevaultRoute = BridgevaultRouteImport.update({
  id: '/bridgevault',
  path: '/bridgevault',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgednaRoute = BridgednaRouteImport.update({
  id: '/bridgedna',
  path: '/bridgedna',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeIntelligenceRoute = BridgeIntelligenceRouteImport.update({
  id: '/bridge-intelligence',
  path: '/bridge-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bridge-intelligence': typeof BridgeIntelligenceRoute
  '/bridgedna': typeof BridgednaRoute
  '/bridgevault': typeof BridgevaultRoute
  '/bridgeworld': typeof BridgeworldRoute
  '/dashboard': typeof DashboardRoute
  '/new-event': typeof NewEventRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bridge-intelligence': typeof BridgeIntelligenceRoute
  '/bridgedna': typeof BridgednaRoute
  '/bridgevault': typeof BridgevaultRoute
  '/bridgeworld': typeof BridgeworldRoute
  '/dashboard': typeof DashboardRoute
  '/new-event': typeof NewEventRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bridge-intelligence': typeof BridgeIntelligenceRoute
  '/bridgedna': typeof BridgednaRoute
  '/bridgevault': typeof BridgevaultRoute
  '/bridgeworld': typeof BridgeworldRoute
  '/dashboard': typeof DashboardRoute
  '/new-event': typeof NewEventRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bridge-intelligence'
    | '/bridgedna'
    | '/bridgevault'
    | '/bridgeworld'
    | '/dashboard'
    | '/new-event'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bridge-intelligence'
    | '/bridgedna'
    | '/bridgevault'
    | '/bridgeworld'
    | '/dashboard'
    | '/new-event'
  id:
    | '__root__'
    | '/'
    | '/bridge-intelligence'
    | '/bridgedna'
    | '/bridgevault'
    | '/bridgeworld'
    | '/dashboard'
    | '/new-event'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BridgeIntelligenceRoute: typeof BridgeIntelligenceRoute
  BridgednaRoute: typeof BridgednaRoute
  BridgevaultRoute: typeof BridgevaultRoute
  BridgeworldRoute: typeof BridgeworldRoute
  DashboardRoute: typeof DashboardRoute
  NewEventRoute: typeof NewEventRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new-event': {
      id: '/new-event'
      path: '/new-event'
      fullPath: '/new-event'
      preLoaderRoute: typeof NewEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridgeworld': {
      id: '/bridgeworld'
      path: '/bridgeworld'
      fullPath: '/bridgeworld'
      preLoaderRoute: typeof BridgeworldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridgevault': {
      id: '/bridgevault'
      path: '/bridgevault'
      fullPath: '/bridgevault'
      preLoaderRoute: typeof BridgevaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridgedna': {
      id: '/bridgedna'
      path: '/bridgedna'
      fullPath: '/bridgedna'
      preLoaderRoute: typeof BridgednaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridge-intelligence': {
      id: '/bridge-intelligence'
      path: '/bridge-intelligence'
      fullPath: '/bridge-intelligence'
      preLoaderRoute: typeof BridgeIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BridgeIntelligenceRoute: BridgeIntelligenceRoute,
  BridgednaRoute: BridgednaRoute,
  BridgevaultRoute: BridgevaultRoute,
  BridgeworldRoute: BridgeworldRoute,
  DashboardRoute: DashboardRoute,
  NewEventRoute: NewEventRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
