/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as VendorPortalRouteImport } from './routes/vendor-portal'
import { Route as TutorialsRouteImport } from './routes/tutorials'
import { Route as TravelRouteImport } from './routes/travel'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as ShareRouteImport } from './routes/share'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GuestsRouteImport } from './routes/guests'
import { Route as GuestPortalRouteImport } from './routes/guest-portal'
import { Route as FundraisingRouteImport } from './routes/fundraising'
import { Route as FilesRouteImport } from './routes/files'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConciergeRouteImport } from './routes/concierge'
import { Route as CollaborationRouteImport } from './routes/collaboration'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as BridgeworldRouteImport } from './routes/bridgeworld'
import { Route as BridgevaultRouteImport } from './routes/bridgevault'
import { Route as BridgestudioRouteImport } from './routes/bridgestudio'
import { Route as BridgepilotRouteImport } from './routes/bridgepilot'
import { Route as BridgepayRouteImport } from './routes/bridgepay'
import { Route as BridgeliveRouteImport } from './routes/bridgelive'
import { Route as BridgegraphRouteImport } from './routes/bridgegraph'
import { Route as BridgednaRouteImport } from './routes/bridgedna'
import { Route as BridgeIntelligenceRouteImport } from './routes/bridge-intelligence'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiPlanningRouteImport } from './routes/ai-planning'
import { Route as AiMemoryRouteImport } from './routes/ai-memory'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminInviteRouteImport } from './routes/admin.invite'
import { Route as AuthenticatedVendorSettingsRouteImport } from './routes/_authenticated/vendor-settings'
import { Route as AuthenticatedVendorProfileBuilderRouteImport } from './routes/_authenticated/vendor-profile-builder'
import { Route as AuthenticatedVendorRouteImport } from './routes/_authenticated/vendor'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDraftsRouteImport } from './routes/_authenticated/drafts'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events/index'
import { Route as AuthenticatedCalendarIndexRouteImport } from './routes/_authenticated/calendar.index'
import { Route as AuthenticatedBookingsIndexRouteImport } from './routes/_authenticated/bookings.index'
import { Route as AuthenticatedSettingsCalendarRouteImport } from './routes/_authenticated/settings.calendar'
import { Route as AuthenticatedEventsNewRouteImport } from './routes/_authenticated/events/new'
import { Route as AuthenticatedEventsAiNewRouteImport } from './routes/_authenticated/events/ai-new'
import { Route as AuthenticatedEventsEventIdRouteImport } from './routes/_authenticated/events/$eventId'
import { Route as AuthenticatedCalendarSettingsRouteImport } from './routes/_authenticated/calendar.settings'
import { Route as AuthenticatedCalendarRequestsRouteImport } from './routes/_authenticated/calendar.requests'
import { Route as AuthenticatedCalendarDashboardRouteImport } from './routes/_authenticated/calendar.dashboard'
import { Route as AuthenticatedBookingsIdRouteImport } from './routes/_authenticated/bookings.$id'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedCalendarEventsIdRouteImport } from './routes/_authenticated/calendar.events.$id'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorPortalRoute = VendorPortalRouteImport.update({
  id: '/vendor-portal',
  path: '/vendor-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialsRoute = TutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestsRoute = GuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestPortalRoute = GuestPortalRouteImport.update({
  id: '/guest-portal',
  path: '/guest-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const FundraisingRoute = FundraisingRouteImport.update({
  id: '/fundraising',
  path: '/fundraising',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciergeRoute = ConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborationRoute = CollaborationRouteImport.update({
  id: '/collaboration',
  path: '/collaboration',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeworldRoute = BridgeworldRouteImport.update({
  id: '/bridgeworld',
  path: '/bridgeworld',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgevaultRoute = BridgevaultRouteImport.update({
  id: '/bridgevault',
  path: '/bridgevault',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgestudioRoute = BridgestudioRouteImport.update({
  id: '/bridgestudio',
  path: '/bridgestudio',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgepilotRoute = BridgepilotRouteImport.update({
  id: '/bridgepilot',
  path: '/bridgepilot',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgepayRoute = BridgepayRouteImport.update({
  id: '/bridgepay',
  path: '/bridgepay',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeliveRoute = BridgeliveRouteImport.update({
  id: '/bridgelive',
  path: '/bridgelive',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgegraphRoute = BridgegraphRouteImport.update({
  id: '/bridgegraph',
  path: '/bridgegraph',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgednaRoute = BridgednaRouteImport.update({
  id: '/bridgedna',
  path: '/bridgedna',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeIntelligenceRoute = BridgeIntelligenceRouteImport.update({
  id: '/bridge-intelligence',
  path: '/bridge-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPlanningRoute = AiPlanningRouteImport.update({
  id: '/ai-planning',
  path: '/ai-planning',
  getParentRoute: () => rootRouteImport,
} as any)
const AiMemoryRoute = AiMemoryRouteImport.update({
  id: '/ai-memory',
  path: '/ai-memory',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInviteRoute = AdminInviteRouteImport.update({
  id: '/admin/invite',
  path: '/admin/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendorSettingsRoute =
  AuthenticatedVendorSettingsRouteImport.update({
    id: '/vendor-settings',
    path: '/vendor-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorProfileBuilderRoute =
  AuthenticatedVendorProfileBuilderRouteImport.update({
    id: '/vendor-profile-builder',
    path: '/vendor-profile-builder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorRoute = AuthenticatedVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDraftsRoute = AuthenticatedDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarIndexRoute =
  AuthenticatedCalendarIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCalendarRoute,
  } as any)
const AuthenticatedBookingsIndexRoute =
  AuthenticatedBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsCalendarRoute =
  AuthenticatedSettingsCalendarRouteImport.update({
    id: '/settings/calendar',
    path: '/settings/calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsNewRoute = AuthenticatedEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsAiNewRoute =
  AuthenticatedEventsAiNewRouteImport.update({
    id: '/events/ai-new',
    path: '/events/ai-new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsEventIdRoute =
  AuthenticatedEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarSettingsRoute =
  AuthenticatedCalendarSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedCalendarRoute,
  } as any)
const AuthenticatedCalendarRequestsRoute =
  AuthenticatedCalendarRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedCalendarRoute,
  } as any)
const AuthenticatedCalendarDashboardRoute =
  AuthenticatedCalendarDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedCalendarRoute,
  } as any)
const AuthenticatedBookingsIdRoute = AuthenticatedBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCalendarEventsIdRoute =
  AuthenticatedCalendarEventsIdRouteImport.update({
    id: '/events/$id',
    path: '/events/$id',
    getParentRoute: () => AuthenticatedCalendarRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/ai-memory': typeof AiMemoryRoute
  '/ai-planning': typeof AiPlanningRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRouteWithChildren
  '/bridge-intelligence': typeof BridgeIntelligenceRoute
  '/bridgedna': typeof BridgednaRoute
  '/bridgegraph': typeof BridgegraphRoute
  '/bridgelive': typeof BridgeliveRoute
  '/bridgepay': typeof BridgepayRoute
  '/bridgepilot': typeof BridgepilotRoute
  '/bridgestudio': typeof BridgestudioRoute
  '/bridgevault': typeof BridgevaultRoute
  '/bridgeworld': typeof BridgeworldRoute
  '/budget': typeof BudgetRoute
  '/collaboration': typeof CollaborationRoute
  '/concierge': typeof ConciergeRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/decisions': typeof DecisionsRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/ecosystem': typeof EcosystemRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/files': typeof FilesRoute
  '/fundraising': typeof FundraisingRoute
  '/guest-portal': typeof GuestPortalRoute
  '/guests': typeof GuestsRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/marketplace': typeof MarketplaceRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/subscription': typeof SubscriptionRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/travel': typeof TravelRoute
  '/tutorials': typeof TutorialsRoute
  '/vendor-portal': typeof VendorPortalRoute
  '/vendors': typeof VendorsRoute
  '/vision': typeof VisionRoute
  '/workspace': typeof WorkspaceRoute
  '/calendar': typeof AuthenticatedCalendarRouteWithChildren
  '/drafts': typeof AuthenticatedDraftsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/vendor': typeof AuthenticatedVendorRoute
  '/vendor-profile-builder': typeof AuthenticatedVendorProfileBuilderRoute
  '/vendor-settings': typeof AuthenticatedVendorSettingsRoute
  '/admin/invite': typeof AdminInviteRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/admin/': typeof AdminIndexRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/calendar/dashboard': typeof AuthenticatedCalendarDashboardRoute
  '/calendar/requests': typeof AuthenticatedCalendarRequestsRoute
  '/calendar/settings': typeof AuthenticatedCalendarSettingsRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/events/ai-new': typeof AuthenticatedEventsAiNewRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/settings/calendar': typeof AuthenticatedSettingsCalendarRoute
  '/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/calendar/': typeof AuthenticatedCalendarIndexRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/calendar/events/$id': typeof AuthenticatedCalendarEventsIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/ai-memory': typeof AiMemoryRoute
  '/ai-planning': typeof AiPlanningRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRouteWithChildren
  '/bridge-intelligence': typeof BridgeIntelligenceRoute
  '/bridgedna': typeof BridgednaRoute
  '/bridgegraph': typeof BridgegraphRoute
  '/bridgelive': typeof BridgeliveRoute
  '/bridgepay': typeof BridgepayRoute
  '/bridgepilot': typeof BridgepilotRoute
  '/bridgestudio': typeof BridgestudioRoute
  '/bridgevault': typeof BridgevaultRoute
  '/bridgeworld': typeof BridgeworldRoute
  '/budget': typeof BudgetRoute
  '/collaboration': typeof CollaborationRoute
  '/concierge': typeof ConciergeRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/decisions': typeof DecisionsRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/ecosystem': typeof EcosystemRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/files': typeof FilesRoute
  '/fundraising': typeof FundraisingRoute
  '/guest-portal': typeof GuestPortalRoute
  '/guests': typeof GuestsRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/marketplace': typeof MarketplaceRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/subscription': typeof SubscriptionRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/travel': typeof TravelRoute
  '/tutorials': typeof TutorialsRoute
  '/vendor-portal': typeof VendorPortalRoute
  '/vendors': typeof VendorsRoute
  '/vision': typeof VisionRoute
  '/workspace': typeof WorkspaceRoute
  '/drafts': typeof AuthenticatedDraftsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/vendor': typeof AuthenticatedVendorRoute
  '/vendor-profile-builder': typeof AuthenticatedVendorProfileBuilderRoute
  '/vendor-settings': typeof AuthenticatedVendorSettingsRoute
  '/admin/invite': typeof AdminInviteRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/admin': typeof AdminIndexRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/calendar/dashboard': typeof AuthenticatedCalendarDashboardRoute
  '/calendar/requests': typeof AuthenticatedCalendarRequestsRoute
  '/calendar/settings': typeof AuthenticatedCalendarSettingsRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/events/ai-new': typeof AuthenticatedEventsAiNewRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/settings/calendar': typeof AuthenticatedSettingsCalendarRoute
  '/bookings': typeof AuthenticatedBookingsIndexRoute
  '/calendar': typeof AuthenticatedCalendarIndexRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/calendar/events/$id': typeof AuthenticatedCalendarEventsIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/ai-memory': typeof AiMemoryRoute
  '/ai-planning': typeof AiPlanningRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRouteWithChildren
  '/bridge-intelligence': typeof BridgeIntelligenceRoute
  '/bridgedna': typeof BridgednaRoute
  '/bridgegraph': typeof BridgegraphRoute
  '/bridgelive': typeof BridgeliveRoute
  '/bridgepay': typeof BridgepayRoute
  '/bridgepilot': typeof BridgepilotRoute
  '/bridgestudio': typeof BridgestudioRoute
  '/bridgevault': typeof BridgevaultRoute
  '/bridgeworld': typeof BridgeworldRoute
  '/budget': typeof BudgetRoute
  '/collaboration': typeof CollaborationRoute
  '/concierge': typeof ConciergeRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/decisions': typeof DecisionsRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/ecosystem': typeof EcosystemRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/files': typeof FilesRoute
  '/fundraising': typeof FundraisingRoute
  '/guest-portal': typeof GuestPortalRoute
  '/guests': typeof GuestsRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/marketplace': typeof MarketplaceRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/subscription': typeof SubscriptionRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/travel': typeof TravelRoute
  '/tutorials': typeof TutorialsRoute
  '/vendor-portal': typeof VendorPortalRoute
  '/vendors': typeof VendorsRoute
  '/vision': typeof VisionRoute
  '/workspace': typeof WorkspaceRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRouteWithChildren
  '/_authenticated/drafts': typeof AuthenticatedDraftsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/vendor': typeof AuthenticatedVendorRoute
  '/_authenticated/vendor-profile-builder': typeof AuthenticatedVendorProfileBuilderRoute
  '/_authenticated/vendor-settings': typeof AuthenticatedVendorSettingsRoute
  '/admin/invite': typeof AdminInviteRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/_authenticated/calendar/dashboard': typeof AuthenticatedCalendarDashboardRoute
  '/_authenticated/calendar/requests': typeof AuthenticatedCalendarRequestsRoute
  '/_authenticated/calendar/settings': typeof AuthenticatedCalendarSettingsRoute
  '/_authenticated/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/_authenticated/events/ai-new': typeof AuthenticatedEventsAiNewRoute
  '/_authenticated/events/new': typeof AuthenticatedEventsNewRoute
  '/_authenticated/settings/calendar': typeof AuthenticatedSettingsCalendarRoute
  '/_authenticated/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/_authenticated/calendar/': typeof AuthenticatedCalendarIndexRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/calendar/events/$id': typeof AuthenticatedCalendarEventsIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/ai-memory'
    | '/ai-planning'
    | '/analytics'
    | '/auth'
    | '/bridge-intelligence'
    | '/bridgedna'
    | '/bridgegraph'
    | '/bridgelive'
    | '/bridgepay'
    | '/bridgepilot'
    | '/bridgestudio'
    | '/bridgevault'
    | '/bridgeworld'
    | '/budget'
    | '/collaboration'
    | '/concierge'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/decisions'
    | '/digital-twin'
    | '/ecosystem'
    | '/faq'
    | '/features'
    | '/files'
    | '/fundraising'
    | '/guest-portal'
    | '/guests'
    | '/help'
    | '/how-it-works'
    | '/marketplace'
    | '/notifications'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/share'
    | '/subscription'
    | '/tasks'
    | '/team'
    | '/terms'
    | '/timeline'
    | '/travel'
    | '/tutorials'
    | '/vendor-portal'
    | '/vendors'
    | '/vision'
    | '/workspace'
    | '/calendar'
    | '/drafts'
    | '/onboarding'
    | '/vendor'
    | '/vendor-profile-builder'
    | '/vendor-settings'
    | '/admin/invite'
    | '/admin/users'
    | '/auth/callback'
    | '/checkout/return'
    | '/admin/'
    | '/bookings/$id'
    | '/calendar/dashboard'
    | '/calendar/requests'
    | '/calendar/settings'
    | '/events/$eventId'
    | '/events/ai-new'
    | '/events/new'
    | '/settings/calendar'
    | '/bookings/'
    | '/calendar/'
    | '/events/'
    | '/calendar/events/$id'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/ai-memory'
    | '/ai-planning'
    | '/analytics'
    | '/auth'
    | '/bridge-intelligence'
    | '/bridgedna'
    | '/bridgegraph'
    | '/bridgelive'
    | '/bridgepay'
    | '/bridgepilot'
    | '/bridgestudio'
    | '/bridgevault'
    | '/bridgeworld'
    | '/budget'
    | '/collaboration'
    | '/concierge'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/decisions'
    | '/digital-twin'
    | '/ecosystem'
    | '/faq'
    | '/features'
    | '/files'
    | '/fundraising'
    | '/guest-portal'
    | '/guests'
    | '/help'
    | '/how-it-works'
    | '/marketplace'
    | '/notifications'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/share'
    | '/subscription'
    | '/tasks'
    | '/team'
    | '/terms'
    | '/timeline'
    | '/travel'
    | '/tutorials'
    | '/vendor-portal'
    | '/vendors'
    | '/vision'
    | '/workspace'
    | '/drafts'
    | '/onboarding'
    | '/vendor'
    | '/vendor-profile-builder'
    | '/vendor-settings'
    | '/admin/invite'
    | '/admin/users'
    | '/auth/callback'
    | '/checkout/return'
    | '/admin'
    | '/bookings/$id'
    | '/calendar/dashboard'
    | '/calendar/requests'
    | '/calendar/settings'
    | '/events/$eventId'
    | '/events/ai-new'
    | '/events/new'
    | '/settings/calendar'
    | '/bookings'
    | '/calendar'
    | '/events'
    | '/calendar/events/$id'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/accessibility'
    | '/ai-memory'
    | '/ai-planning'
    | '/analytics'
    | '/auth'
    | '/bridge-intelligence'
    | '/bridgedna'
    | '/bridgegraph'
    | '/bridgelive'
    | '/bridgepay'
    | '/bridgepilot'
    | '/bridgestudio'
    | '/bridgevault'
    | '/bridgeworld'
    | '/budget'
    | '/collaboration'
    | '/concierge'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/decisions'
    | '/digital-twin'
    | '/ecosystem'
    | '/faq'
    | '/features'
    | '/files'
    | '/fundraising'
    | '/guest-portal'
    | '/guests'
    | '/help'
    | '/how-it-works'
    | '/marketplace'
    | '/notifications'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/share'
    | '/subscription'
    | '/tasks'
    | '/team'
    | '/terms'
    | '/timeline'
    | '/travel'
    | '/tutorials'
    | '/vendor-portal'
    | '/vendors'
    | '/vision'
    | '/workspace'
    | '/_authenticated/calendar'
    | '/_authenticated/drafts'
    | '/_authenticated/onboarding'
    | '/_authenticated/vendor'
    | '/_authenticated/vendor-profile-builder'
    | '/_authenticated/vendor-settings'
    | '/admin/invite'
    | '/admin/users'
    | '/auth/callback'
    | '/checkout/return'
    | '/admin/'
    | '/_authenticated/bookings/$id'
    | '/_authenticated/calendar/dashboard'
    | '/_authenticated/calendar/requests'
    | '/_authenticated/calendar/settings'
    | '/_authenticated/events/$eventId'
    | '/_authenticated/events/ai-new'
    | '/_authenticated/events/new'
    | '/_authenticated/settings/calendar'
    | '/_authenticated/bookings/'
    | '/_authenticated/calendar/'
    | '/_authenticated/events/'
    | '/_authenticated/calendar/events/$id'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AiMemoryRoute: typeof AiMemoryRoute
  AiPlanningRoute: typeof AiPlanningRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRouteWithChildren
  BridgeIntelligenceRoute: typeof BridgeIntelligenceRoute
  BridgednaRoute: typeof BridgednaRoute
  BridgegraphRoute: typeof BridgegraphRoute
  BridgeliveRoute: typeof BridgeliveRoute
  BridgepayRoute: typeof BridgepayRoute
  BridgepilotRoute: typeof BridgepilotRoute
  BridgestudioRoute: typeof BridgestudioRoute
  BridgevaultRoute: typeof BridgevaultRoute
  BridgeworldRoute: typeof BridgeworldRoute
  BudgetRoute: typeof BudgetRoute
  CollaborationRoute: typeof CollaborationRoute
  ConciergeRoute: typeof ConciergeRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRoute
  DecisionsRoute: typeof DecisionsRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  EcosystemRoute: typeof EcosystemRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  FilesRoute: typeof FilesRoute
  FundraisingRoute: typeof FundraisingRoute
  GuestPortalRoute: typeof GuestPortalRoute
  GuestsRoute: typeof GuestsRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MarketplaceRoute: typeof MarketplaceRoute
  NotificationsRoute: typeof NotificationsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  ShareRoute: typeof ShareRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TasksRoute: typeof TasksRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  TimelineRoute: typeof TimelineRoute
  TravelRoute: typeof TravelRoute
  TutorialsRoute: typeof TutorialsRoute
  VendorPortalRoute: typeof VendorPortalRoute
  VendorsRoute: typeof VendorsRoute
  VisionRoute: typeof VisionRoute
  WorkspaceRoute: typeof WorkspaceRoute
  AdminInviteRoute: typeof AdminInviteRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-portal': {
      id: '/vendor-portal'
      path: '/vendor-portal'
      fullPath: '/vendor-portal'
      preLoaderRoute: typeof VendorPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials': {
      id: '/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof TutorialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guests': {
      id: '/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof GuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-portal': {
      id: '/guest-portal'
      path: '/guest-portal'
      fullPath: '/guest-portal'
      preLoaderRoute: typeof GuestPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundraising': {
      id: '/fundraising'
      path: '/fundraising'
      fullPath: '/fundraising'
      preLoaderRoute: typeof FundraisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concierge': {
      id: '/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof ConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaboration': {
      id: '/collaboration'
      path: '/collaboration'
      fullPath: '/collaboration'
      preLoaderRoute: typeof CollaborationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridgeworld': {
      id: '/bridgeworld'
      path: '/bridgeworld'
      fullPath: '/bridgeworld'
      preLoaderRoute: typeof BridgeworldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridgevault': {
      id: '/bridgevault'
      path: '/bridgevault'
      fullPath: '/bridgevault'
      preLoaderRoute: typeof BridgevaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridgestudio': {
      id: '/bridgestudio'
      path: '/bridgestudio'
      fullPath: '/bridgestudio'
      preLoaderRoute: typeof BridgestudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridgepilot': {
      id: '/bridgepilot'
      path: '/bridgepilot'
      fullPath: '/bridgepilot'
      preLoaderRoute: typeof BridgepilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridgepay': {
      id: '/bridgepay'
      path: '/bridgepay'
      fullPath: '/bridgepay'
      preLoaderRoute: typeof BridgepayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridgelive': {
      id: '/bridgelive'
      path: '/bridgelive'
      fullPath: '/bridgelive'
      preLoaderRoute: typeof BridgeliveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridgegraph': {
      id: '/bridgegraph'
      path: '/bridgegraph'
      fullPath: '/bridgegraph'
      preLoaderRoute: typeof BridgegraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridgedna': {
      id: '/bridgedna'
      path: '/bridgedna'
      fullPath: '/bridgedna'
      preLoaderRoute: typeof BridgednaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridge-intelligence': {
      id: '/bridge-intelligence'
      path: '/bridge-intelligence'
      fullPath: '/bridge-intelligence'
      preLoaderRoute: typeof BridgeIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-planning': {
      id: '/ai-planning'
      path: '/ai-planning'
      fullPath: '/ai-planning'
      preLoaderRoute: typeof AiPlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-memory': {
      id: '/ai-memory'
      path: '/ai-memory'
      fullPath: '/ai-memory'
      preLoaderRoute: typeof AiMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invite': {
      id: '/admin/invite'
      path: '/admin/invite'
      fullPath: '/admin/invite'
      preLoaderRoute: typeof AdminInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendor-settings': {
      id: '/_authenticated/vendor-settings'
      path: '/vendor-settings'
      fullPath: '/vendor-settings'
      preLoaderRoute: typeof AuthenticatedVendorSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor-profile-builder': {
      id: '/_authenticated/vendor-profile-builder'
      path: '/vendor-profile-builder'
      fullPath: '/vendor-profile-builder'
      preLoaderRoute: typeof AuthenticatedVendorProfileBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor': {
      id: '/_authenticated/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AuthenticatedVendorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drafts': {
      id: '/_authenticated/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof AuthenticatedDraftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar/': {
      id: '/_authenticated/calendar/'
      path: '/'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AuthenticatedCalendarIndexRouteImport
      parentRoute: typeof AuthenticatedCalendarRoute
    }
    '/_authenticated/bookings/': {
      id: '/_authenticated/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AuthenticatedBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/calendar': {
      id: '/_authenticated/settings/calendar'
      path: '/settings/calendar'
      fullPath: '/settings/calendar'
      preLoaderRoute: typeof AuthenticatedSettingsCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/new': {
      id: '/_authenticated/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AuthenticatedEventsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/ai-new': {
      id: '/_authenticated/events/ai-new'
      path: '/events/ai-new'
      fullPath: '/events/ai-new'
      preLoaderRoute: typeof AuthenticatedEventsAiNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$eventId': {
      id: '/_authenticated/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar/settings': {
      id: '/_authenticated/calendar/settings'
      path: '/settings'
      fullPath: '/calendar/settings'
      preLoaderRoute: typeof AuthenticatedCalendarSettingsRouteImport
      parentRoute: typeof AuthenticatedCalendarRoute
    }
    '/_authenticated/calendar/requests': {
      id: '/_authenticated/calendar/requests'
      path: '/requests'
      fullPath: '/calendar/requests'
      preLoaderRoute: typeof AuthenticatedCalendarRequestsRouteImport
      parentRoute: typeof AuthenticatedCalendarRoute
    }
    '/_authenticated/calendar/dashboard': {
      id: '/_authenticated/calendar/dashboard'
      path: '/dashboard'
      fullPath: '/calendar/dashboard'
      preLoaderRoute: typeof AuthenticatedCalendarDashboardRouteImport
      parentRoute: typeof AuthenticatedCalendarRoute
    }
    '/_authenticated/bookings/$id': {
      id: '/_authenticated/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof AuthenticatedBookingsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calendar/events/$id': {
      id: '/_authenticated/calendar/events/$id'
      path: '/events/$id'
      fullPath: '/calendar/events/$id'
      preLoaderRoute: typeof AuthenticatedCalendarEventsIdRouteImport
      parentRoute: typeof AuthenticatedCalendarRoute
    }
  }
}

interface AuthenticatedCalendarRouteChildren {
  AuthenticatedCalendarDashboardRoute: typeof AuthenticatedCalendarDashboardRoute
  AuthenticatedCalendarRequestsRoute: typeof AuthenticatedCalendarRequestsRoute
  AuthenticatedCalendarSettingsRoute: typeof AuthenticatedCalendarSettingsRoute
  AuthenticatedCalendarIndexRoute: typeof AuthenticatedCalendarIndexRoute
  AuthenticatedCalendarEventsIdRoute: typeof AuthenticatedCalendarEventsIdRoute
}

const AuthenticatedCalendarRouteChildren: AuthenticatedCalendarRouteChildren = {
  AuthenticatedCalendarDashboardRoute: AuthenticatedCalendarDashboardRoute,
  AuthenticatedCalendarRequestsRoute: AuthenticatedCalendarRequestsRoute,
  AuthenticatedCalendarSettingsRoute: AuthenticatedCalendarSettingsRoute,
  AuthenticatedCalendarIndexRoute: AuthenticatedCalendarIndexRoute,
  AuthenticatedCalendarEventsIdRoute: AuthenticatedCalendarEventsIdRoute,
}

const AuthenticatedCalendarRouteWithChildren =
  AuthenticatedCalendarRoute._addFileChildren(
    AuthenticatedCalendarRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRouteWithChildren
  AuthenticatedDraftsRoute: typeof AuthenticatedDraftsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedVendorRoute: typeof AuthenticatedVendorRoute
  AuthenticatedVendorProfileBuilderRoute: typeof AuthenticatedVendorProfileBuilderRoute
  AuthenticatedVendorSettingsRoute: typeof AuthenticatedVendorSettingsRoute
  AuthenticatedBookingsIdRoute: typeof AuthenticatedBookingsIdRoute
  AuthenticatedEventsEventIdRoute: typeof AuthenticatedEventsEventIdRoute
  AuthenticatedEventsAiNewRoute: typeof AuthenticatedEventsAiNewRoute
  AuthenticatedEventsNewRoute: typeof AuthenticatedEventsNewRoute
  AuthenticatedSettingsCalendarRoute: typeof AuthenticatedSettingsCalendarRoute
  AuthenticatedBookingsIndexRoute: typeof AuthenticatedBookingsIndexRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRouteWithChildren,
  AuthenticatedDraftsRoute: AuthenticatedDraftsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedVendorRoute: AuthenticatedVendorRoute,
  AuthenticatedVendorProfileBuilderRoute:
    AuthenticatedVendorProfileBuilderRoute,
  AuthenticatedVendorSettingsRoute: AuthenticatedVendorSettingsRoute,
  AuthenticatedBookingsIdRoute: AuthenticatedBookingsIdRoute,
  AuthenticatedEventsEventIdRoute: AuthenticatedEventsEventIdRoute,
  AuthenticatedEventsAiNewRoute: AuthenticatedEventsAiNewRoute,
  AuthenticatedEventsNewRoute: AuthenticatedEventsNewRoute,
  AuthenticatedSettingsCalendarRoute: AuthenticatedSettingsCalendarRoute,
  AuthenticatedBookingsIndexRoute: AuthenticatedBookingsIndexRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AiMemoryRoute: AiMemoryRoute,
  AiPlanningRoute: AiPlanningRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRouteWithChildren,
  BridgeIntelligenceRoute: BridgeIntelligenceRoute,
  BridgednaRoute: BridgednaRoute,
  BridgegraphRoute: BridgegraphRoute,
  BridgeliveRoute: BridgeliveRoute,
  BridgepayRoute: BridgepayRoute,
  BridgepilotRoute: BridgepilotRoute,
  BridgestudioRoute: BridgestudioRoute,
  BridgevaultRoute: BridgevaultRoute,
  BridgeworldRoute: BridgeworldRoute,
  BudgetRoute: BudgetRoute,
  CollaborationRoute: CollaborationRoute,
  ConciergeRoute: ConciergeRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRoute,
  DecisionsRoute: DecisionsRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  EcosystemRoute: EcosystemRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  FilesRoute: FilesRoute,
  FundraisingRoute: FundraisingRoute,
  GuestPortalRoute: GuestPortalRoute,
  GuestsRoute: GuestsRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  MarketplaceRoute: MarketplaceRoute,
  NotificationsRoute: NotificationsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  ShareRoute: ShareRoute,
  SubscriptionRoute: SubscriptionRoute,
  TasksRoute: TasksRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  TimelineRoute: TimelineRoute,
  TravelRoute: TravelRoute,
  TutorialsRoute: TutorialsRoute,
  VendorPortalRoute: VendorPortalRoute,
  VendorsRoute: VendorsRoute,
  VisionRoute: VisionRoute,
  WorkspaceRoute: WorkspaceRoute,
  AdminInviteRoute: AdminInviteRoute,
  AdminUsersRoute: AdminUsersRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
